name: CI [PR Validation]

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install deps
        run: npm ci

      - name: lint check
        run: npm run lint

      - name: Prettier check
        run: npm run format:check
        continue-on-error: true

      - name: Typescript check
        run: npm run type-check

  test:
    name: tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install deps
        run: npm ci

      - name: unit tests
        run: npm run test:unit

      - name: integration tests
        run: npm run test:integration

  build:
    name: build-check
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install deps
        run: npm ci

      - name: build app
        run: npm run build
